### PR TITLE
Update network module interface

### PR DESCRIPTION
**Pull request by fntsrlike**

### CODE REVIEW

**Comment by tjjh89017** [comment]
Rename `Packable` to `Packet` ?

**Comment by fntsrlike** [comment]
`Packet` 是介面還是抽象類別？

**Comment by tjjh89017** [comment]
`Packet` is a class with `pack()` & `unpack()` methods.
Scene needs to new a `Packet` with data they want, and send `Packet` to you.
What you need to do just call `pack()` & `unpack()`

**Comment by fntsrlike** [comment]
所你要我先留空內容給這兩個類別嗎


還是你等等再提一個 PR，針對這個項目。我這個 PR 就先不再更動了

**Comment by tjjh89017** [comment]
You can do that. I will implement the features after discussing with Scene and Input

**Comment by fntsrlike** [comment]
那就請你先 Merge 這邊吧

**Comment by tjjh89017** [comment]
Ok

**Pull request merged**
